top/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from models import session, Job

top = Blueprint(
    "top",
    __name__,
    template_folder="templates",
)

@top.route("/")
@login_required
def index():
    jobs = session.query(Job).filter(Job.invoiced == 0).all()
    return render_template("top/index.html", jobs = jobs)

top/templates/top/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0,width=device-width">
        <link rel="shortcut icon" href="{{ url_for('static',filename='favicon.ico')}}">
        <title>{% block title %}{% endblock %} - invoicee</title>
        <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}">
    </head>
    <body>
        <header>
            <nav>
                <h1>invoicee</h1>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('top.index') }}">ジョブ一覧</a>
                    <a href="{{ url_for('create.index') }}">ジョブを作成</a>
                    <a href="{{ url_for('update.index') }}">ジョブを更新</a>
                    <a href="{{ url_for('invoice.index') }}">請求書を発行</a>
                    <a href="{{ url_for('admin.index') }}">管理画面</a>
                    <a href="{{ url_for('logout.index') }}">ログアウト</a>
                {% else %}
                    <a href="{{ url_for('login.index') }}">ログイン</a>
                    <a href="{{ url_for('register.index') }}">ユーザー登録</a>
                {% endif %}
            </nav>
        </header>
        <main>
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

top/templates/top/index.html
{% extends "top/base.html" %}
{% block title %}ジョブ一覧{% endblock %}

{% block content %}
<h2>ジョブ一覧</h2>
<table>
    <thead>
        <th>ジョブタイトル</th>
        <th>受注日</th>
        <th>クライアント</th>
    </thead>
    <tbody>
        {% for job in jobs %}
        <tr>
            <td>{{ job['title'] }}</td>
            <td>{{ job['created'] }}</td>
            <td>{{ job['client'].client_name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}